#!/bin/bash

# Load in the configfile
. ../configfile.txt

###########
# Perform check on acacia to compare with the local workflow check
##########
# Set the CSV file name  
CSV=$results/draftcheck-acacia.$DATE.csv

#Add headings
echo OGID,AcaNum,AcaSize,AcaBytes | tee -a $CSV

# Read the OGLIST from the data audit
OGLIST_FILE=$results/OGLIST.txt


# Loop through each OGID in the OGLIST file
while IFS= read -r OGID; do
  # Get the sizes from rclone for each location
  SIZES=$(echo $(rclone size pawsey0812:oceanomics-genomes/genomes.v2/$OGID | sed 's/Total/|-- Acacia/g'))
  
  # Format and append the results to the CSV
  echo $OGID $SIZES | sed -E 's/(\(|\))//g' | awk '{print $1,$6,$10 $11,$12;}' | sed 's/ /,/g' | tee -a $CSV
done < "$OGLIST_FILE"